// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHNdVcLdkdtUPYM16eo2M5Fplncn-KZg',
    appId: '1:466725686767:web:724eafd05c7ac0a45ffa1a',
    messagingSenderId: '466725686767',
    projectId: 'siak-mhs-azzam',
    authDomain: 'siak-mhs-azzam.firebaseapp.com',
    storageBucket: 'siak-mhs-azzam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkKQ50Au8uKK2JFzYpJ7mx5CoWzpnxagI',
    appId: '1:466725686767:android:71cd43493db065c05ffa1a',
    messagingSenderId: '466725686767',
    projectId: 'siak-mhs-azzam',
    storageBucket: 'siak-mhs-azzam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcD229m4kI9I6IxoCACAuS6H5u4rLOGng',
    appId: '1:466725686767:ios:9e98858969b333255ffa1a',
    messagingSenderId: '466725686767',
    projectId: 'siak-mhs-azzam',
    storageBucket: 'siak-mhs-azzam.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcD229m4kI9I6IxoCACAuS6H5u4rLOGng',
    appId: '1:466725686767:ios:98150cb9fb5d2a485ffa1a',
    messagingSenderId: '466725686767',
    projectId: 'siak-mhs-azzam',
    storageBucket: 'siak-mhs-azzam.appspot.com',
    iosBundleId: 'com.example.uts.RunnerTests',
  );
}
